services:
  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - .:/frontend
      - ./node_modules:/frontend/node_modules
    ports:
      - 80:80
    restart: unless-stopped
    tty: true
    command: npm start

  backend:
    container_name: backend
    build: ./backend
    ports:
      - 3000:3000
    networks:
      - backend

  database:
    container_name: db
    image: postgres:latest
    volumes:
      - db:/var/lib/postgresql
    env_file:
      - .env
    networks:
      - backend

  pgadmin:
    container_name: pg-admin-archery
    image: dpage/pgadmin4
    restart: always
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    env_file:
      - .env
    ports:
      - "5050:80"
    networks:
      - backend

volumes:
  pgadmin-data:
    driver: local
  db:
    driver: local

networks:
  backend:
    driver: bridge
